labels:
  app-group: jarvis
  language: rust

version:
  semver:
    major: 0
    minor: 2

stages:
  build-lint-and-package:
    parallelStages:
      lint-helm-chart:
        image: extensions/helm:stable
        action: lint

      package-helm-chart:
        image: extensions/helm:stable
        action: package

  clone-charts-repo:
    image: extensions/git-clone:stable
    repo: helm-charts
    branch: master

  publish-helm-chart:
    image: extensions/helm:stable
    action: publish
    repoUrl: https://helm.jorritsalverda.com/

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - jsalverda

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - jsalverda

  # test-helm-chart:
  #   services:
  #   - name: kubernetes
  #     image: bsycorp/kind:latest-1.17
  #     readiness:
  #       path: /kubernetes-ready
  #       port: 10080
  #   image: extensions/helm:stable
  #   action: test
  #   values: |-
  #     secret:
  #       gcpServiceAccountKeyfile: '{}'