# Default values for jarvis-wallbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  ttlSecondsAfterFinished: 3600

config:
  timeoutSeconds: 10
  bqEnable: false
  bqInit: true
  bqProjectID: gcp-project-id
  bqDataset: jarvis
  bqTable: jarvis_measurements
  configYaml: |
    location: My Home
    entityType: ENTITY_TYPE_DEVICE
    entityName: Wallbox PulsarPlus

secret:
  gcpServiceAccountKeyfile: '{}'
  username: ''
  password: ''

logFormat: json

image:
  repository: jsalverda/jarvis-wallbox-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether roles and bindings should be created
  enable: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
