apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-wallbox-exporter.fullname" . }}
  labels:
    {{- include "jarvis-wallbox-exporter.labels" . | nindent 4 }}
data:
  nats-host:  {{ .Values.config.natsHost | quote }}
  nats-subject:  {{ .Values.config.natsSubject | quote }}
  config.yaml: |
    {{- with .Values.config.configYaml }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}