apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis-wallbox-exporter.fullname" . }}
  labels:
    {{- include "jarvis-wallbox-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.username | toString | b64enc }}
  password: {{ .Values.secret.password | toString | b64enc }}