name: Build Docker Image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build the Docker image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from jsalverda/jarvis-wallbox-exporter:dlc-builder --tag jsalverda/jarvis-wallbox-exporter:dlc-builder --target builder --file Dockerfile .
          # docker push jsalverda/jarvis-wallbox-exporter:dlc-builder
          docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from jsalverda/jarvis-wallbox-exporter:dlc-builder --cache-from jsalverda/jarvis-wallbox-exporter:dlc --tag jsalverda/jarvis-wallbox-exporter:dlc --tag jsalverda/jarvis-wallbox-exporter:$TAG --file Dockerfile .
          # docker push jsalverda/jarvis-wallbox-exporter:dlc
          # docker push jsalverda/jarvis-wallbox-exporter:$TAG
